# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Don't Move, Improve! 2017
email: hello@clippings.com
description: > # this means to ignore newlines until "baseurl:"
    Clippings.com has partnered with New London Architecture
    to create the Don't Move Improve - Shop the Look website,
    which enables anyone inspired by the Don't Move Improve projects
    to discover and buy the furniture and lighting that's featured in each home.
    The showcase connects to the enormous catalogue of furniture and
    lighting products listed on Clippings.com.
baseurl: "/dont-move-improve" # the subpath of your site, e.g. /blog
url: "https://clippings.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: ClippingsDesign
github_username:  clippings

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock

permalink: none
timezone: Europe/London

collections:
  projects:
    permalink: /:title
    output: true
  images:
    output: true
  tags:
    permalink: /:title
    output: true

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: _projects
      type: projects
    values:
      layout: project
  -
    scope:
      path: _tags
      type: tags
    values:
      layout: default

trackingCode: UA-73819275-3

sass:
    sass_dir: _sass
    style: expanded
